export { default as Selection} from './Selection'
export { default as Strat} from './Strat'
export { default as Map} from './Map'
export { default as Error} from './Error'
export { default as Landing} from './Landing'
export { default as Login } from './Login'
export { default as AddStrat } from './AddStrat'
export { default as Register } from './Register'
export { default as Admin } from './Admin'
export { default as AllStrats } from './AllStrats'

